language: python

python:
  - 3.5
  - 3.6

branches:
  # only master, canary, and tagged commits
  only:
    - master
    - canary
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - ".tox"

install:
  - pip install tox-travis

script:
  - tox -- --slow --cov-report=xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -c

deploy:
  provider: pypi
  user: "Tektronix"
  password:
    secure: "<encrypted password>"
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
