language: python

branches:
  # only master, canary, and tagged commits
  only:
    - master
    - canary
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - ".tox"

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36

install:
  - pip install -e .[dev,test]

script:
  - tox -- --slow --cov-report=xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -c
